### ISSUE TITLE
Sample Release Checklist to improve Release Automation

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/TSC#178]
Creating this Work in Progress checklist based on the [release doc](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/RELEASING.md) to capture what main activities happen during a release, and to annotate which activities can and should be automated in some fashion.  This should serve to streamline release activities and help release champions complete all the required tasks.

One Week Prior to Release:
- [ ] **Disable nightly testing** to free up resources and ensure no competing jobs during release week
- [ ] **Run a trial release pipeline** to ensure less surprises on release day

Release Week Checklist:
- [ ] **Add website banner** (_automate_* via github workflow - champion creates a website issue (likely based on a template), on creation of a website issue with particular subject and contents (enforced by a template), a workflow is triggered which creates a PR for the website, similar to this [example PR](https://github.com/AdoptOpenJDK/openjdk-website/pull/702/files))
- [ ] **Launch build pipelines** for each version being released [(as per release doc](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/RELEASING.md#steps-for-every-version)) once release tags are available via [launch page](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/build) in Jenkins.  Typically been separating hotspot and openj9 pipelines in release week.  Capture pertinent info in a table per implementation.
- [ ] **Summarize test results**.  Find each launched build pipeline in [TRSS](https://trss.adoptopenjdk.net/) to view a summary of test results.  Create a summary of test failures per pipeline to add to the [Promote release issue](https://github.com/AdoptOpenJDK/TSC/issues/new?assignees=&labels=&template=promote-release.md&title=Promote+AdoptOpenJDK+Version+%3Cx%3E) in the TSC repo which can be revamped to include a (shorter version of this checklist and ideally contains a succinct table as per example below, you can use [trss-parser](https://www.npmjs.com/package/trss-parser).  (_automate_* via github workflow or Jenkins job trigger to add a comment/table to TSC release issue)
- [ ] **Triage** each build and test failure (using [Triage guidelines](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/doc/Triage.md)) and determine blocking or non-blocking.  
- [ ] **Fix** blocking failures if they exist.
- [ ] **Get TSC 'ready to publish' approval**, once no blocking failures exist.
- [ ] **Publish the release** (run the restricted access [release tool job](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/) on Jenkins)
- [ ] **Verify binaries published successfully** to github releases repo and website (_automate_*, this could also be an automated test)
- [ ] **Update support page** (_automate_* github workflow to create a PR to update [support.handlebars](https://github.com/AdoptOpenJDK/openjdk-website/blob/master/src/handlebars/support.handlebars))
- [ ] **Update release notes** (_automate_* - github workflow to create update for [release notes page](https://adoptopenjdk.net/release_notes.html))
- [ ] **Run homebrew-cask_updater** (via [Jenkins homebrew-cask_updater job link](https://ci.adoptopenjdk.net/job/homebrew-cask_updater/)) once binaries published successfully (this can be automated / triggered by a test for published artifacts)
- [ ] **Publicize the release** via Slack #release channel and Twitter (can be partially automated)

Hotspot
|Job name / ID |scmReference/tag|Other Args if not defaults| Summarized Results | Published |
| --- | --- | --- | --- | --- | 
| [jdk8 Pipeline ID](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline) |  |  | |  |
| [jdk11 Pipeline ID](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline) |  |  | | |
| [jdk15 Pipeline ID](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk15-pipeline) |  |  | | |
|  |  |  | | |

OpenJ9
|Job name / ID |scmReference/tag|Other Args if not defaults| Summarized Results |Published |
| --- | --- | --- | --- | --- |
| [jdk8 Pipeline ID](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline) |  |  | |  |
| [jdk11 Pipeline ID](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline) |  |  | |  |
| [jdk15 Pipeline ID](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk15-pipeline) |  |  | |  |
|  |  |  | |  |

**Comment by smlambert** [comment]
This issue relates to https://github.com/AdoptOpenJDK/TSC/issues/158 especially on the section of fully defining/documenting input arguments to build and publish steps in the release workflow and as part of realizing a fully verifiable build process.

**Comment by smlambert** [comment]
Still need to understand and know what happens for the docker jobs and add that to the checklist.

**Comment by tellison** [comment]
Consider adding in a task, one week prior to release, to 

- [ ] [**Update list of CA certificates**](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/security/README.md) if required.

**Comment by smlambert** [comment]
re: https://github.com/AdoptOpenJDK/TSC/issues/178#issuecomment-808364137 this is not in the [release doc ](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/RELEASING.md)(which is what I am basing the checklist off of).  Should add it there and have the checklist reflect it.
